"""initial attendance schema

Revision ID: c35e8b617a08
Revises:
Create Date: 2026-10-01 07:27:32.185218
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c35e8b617a08"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "laboratories",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_laboratories")),
        sa.UniqueConstraint("code", name="uq_laboratories_code"),
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name="uq_roles_code"),
    )
    op.create_table(
        "students",
        sa.Column("student_number", sa.String(length=32), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint("student_number", name="uq_students_student_number"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column(
            "before_state",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "after_state",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_actor_created_at",
        "audit_logs",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_entity_created_at",
        "audit_logs",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "classes",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("grade", sa.SmallInteger(), nullable=False),
        sa.Column("academic_year", sa.String(length=9), nullable=False),
        sa.Column("homeroom_teacher_id", sa.Uuid(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "grade BETWEEN 1 AND 12", name=op.f("ck_classes_grade_range")
        ),
        sa.ForeignKeyConstraint(
            ["homeroom_teacher_id"],
            ["users.id"],
            name=op.f("fk_classes_homeroom_teacher_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
        sa.UniqueConstraint(
            "code", "academic_year", name="uq_classes_code_academic_year"
        ),
    )
    op.create_index(
        "ix_classes_homeroom_teacher_id",
        "classes",
        ["homeroom_teacher_id"],
        unique=False,
    )
    op.create_table(
        "devices",
        sa.Column("laboratory_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("device_type", sa.String(length=32), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "device_type IN ('edge_pc', 'camera_gateway')",
            name=op.f("ck_devices_device_type"),
        ),
        sa.ForeignKeyConstraint(
            ["laboratory_id"],
            ["laboratories.id"],
            name=op.f("fk_devices_laboratory_id_laboratories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
    )
    op.create_index(
        "ix_devices_laboratory_id", "devices", ["laboratory_id"], unique=False
    )
    op.create_table(
        "face_templates",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column(
            "quality_metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_face_templates_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_user_id"],
            ["users.id"],
            name=op.f("fk_face_templates_revoked_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_face_templates_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_face_templates")),
    )
    op.create_index(
        "ix_face_templates_created_by_user_id",
        "face_templates",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_face_templates_revoked_by_user_id",
        "face_templates",
        ["revoked_by_user_id"],
        unique=False,
    )
    op.create_index(
        "uq_face_templates_active_student_model_version",
        "face_templates",
        ["student_id", "model_name", "model_version"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
        sqlite_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("granted_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
            name=op.f("fk_user_roles_granted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_user_roles_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_roles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_index("ix_user_roles_role_id", "user_roles", ["role_id"], unique=False)
    op.create_table(
        "class_students",
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column(
            "enrolled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_class_students_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_class_students_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "class_id", "student_id", name=op.f("pk_class_students")
        ),
    )
    op.create_index(
        "ix_class_students_student_id", "class_students", ["student_id"], unique=False
    )
    op.create_table(
        "practicum_schedules",
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("laboratory_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_user_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(length=120), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("timezone_name", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_through", sa.Date(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_through IS NULL OR effective_through >= effective_from",
            name=op.f("ck_practicum_schedules_schedule_date_order"),
        ),
        sa.CheckConstraint(
            "start_time < end_time",
            name=op.f("ck_practicum_schedules_schedule_time_order"),
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 0 AND 6", name=op.f("ck_practicum_schedules_weekday_range")
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_practicum_schedules_class_id_classes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["laboratory_id"],
            ["laboratories.id"],
            name=op.f("fk_practicum_schedules_laboratory_id_laboratories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_user_id"],
            ["users.id"],
            name=op.f("fk_practicum_schedules_teacher_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practicum_schedules")),
    )
    op.create_index(
        "ix_practicum_schedules_class_weekday",
        "practicum_schedules",
        ["class_id", "weekday"],
        unique=False,
    )
    op.create_index(
        "ix_practicum_schedules_laboratory_weekday",
        "practicum_schedules",
        ["laboratory_id", "weekday"],
        unique=False,
    )
    op.create_index(
        "ix_practicum_schedules_teacher_user_id",
        "practicum_schedules",
        ["teacher_user_id"],
        unique=False,
    )
    op.create_table(
        "attendance_sessions",
        sa.Column("practicum_schedule_id", sa.Uuid(), nullable=False),
        sa.Column("opened_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            "opened_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "grace_period_minutes",
            sa.SmallInteger(),
            server_default=sa.text("15"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'closed', 'cancelled')",
            name=op.f("ck_attendance_sessions_session_status"),
        ),
        sa.CheckConstraint(
            "closed_at IS NULL OR closed_at >= opened_at",
            name=op.f("ck_attendance_sessions_session_close_after_open"),
        ),
        sa.CheckConstraint(
            "grace_period_minutes >= 0",
            name=op.f("ck_attendance_sessions_grace_period_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_user_id"],
            ["users.id"],
            name=op.f("fk_attendance_sessions_opened_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["practicum_schedule_id"],
            ["practicum_schedules.id"],
            name=op.f(
                "fk_attendance_sessions_practicum_schedule_id_practicum_schedules"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_sessions")),
    )
    op.create_index(
        "ix_attendance_sessions_opened_by_user_id",
        "attendance_sessions",
        ["opened_by_user_id"],
        unique=False,
    )
    op.create_index(
        "uq_attendance_sessions_active_schedule",
        "attendance_sessions",
        ["practicum_schedule_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "recognition_events",
        sa.Column("event_uuid", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("recognized_student_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("margin", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column(
            "quality_metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome != 'matched' OR recognized_student_id IS NOT NULL",
            name=op.f("ck_recognition_events_matched_event_has_student"),
        ),
        sa.CheckConstraint(
            "outcome IN ('matched', 'ambiguous', 'no_match', 'error')",
            name=op.f("ck_recognition_events_event_outcome"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_recognition_events_confidence_range"),
        ),
        sa.CheckConstraint(
            "margin IS NULL OR (margin >= 0 AND margin <= 1)",
            name=op.f("ck_recognition_events_margin_range"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_recognition_events_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recognized_student_id"],
            ["students.id"],
            name=op.f("fk_recognition_events_recognized_student_id_students"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["attendance_sessions.id"],
            name=op.f("fk_recognition_events_session_id_attendance_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recognition_events")),
        sa.UniqueConstraint("event_uuid", name="uq_recognition_events_event_uuid"),
    )
    op.create_index(
        "ix_recognition_events_device_occurred_at",
        "recognition_events",
        ["device_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_recognition_events_session_occurred_at",
        "recognition_events",
        ["session_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_recognition_events_student_occurred_at",
        "recognition_events",
        ["recognized_student_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "session_students",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("student_number_snapshot", sa.String(length=32), nullable=False),
        sa.Column("full_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column(
            "snapshot_taken_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["attendance_sessions.id"],
            name=op.f("fk_session_students_session_id_attendance_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_session_students_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "session_id", "student_id", name=op.f("pk_session_students")
        ),
    )
    op.create_index(
        "ix_session_students_student_id",
        "session_students",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "attendance_records",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("recognition_event_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source = 'face_recognition' AND recognition_event_id IS NOT NULL) OR "
            "(source IN ('manual', 'system') AND recognition_event_id IS NULL)",
            name=op.f("ck_attendance_records_attendance_source_event_consistency"),
        ),
        sa.CheckConstraint(
            "source IN ('face_recognition', 'manual', 'system')",
            name=op.f("ck_attendance_records_attendance_source"),
        ),
        sa.CheckConstraint(
            "status IN ('present', 'late', 'absent', 'excused')",
            name=op.f("ck_attendance_records_attendance_status"),
        ),
        sa.ForeignKeyConstraint(
            ["recognition_event_id"],
            ["recognition_events.id"],
            name=op.f("fk_attendance_records_recognition_event_id_recognition_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            name=op.f("fk_attendance_records_recorded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["attendance_sessions.id"],
            name=op.f("fk_attendance_records_session_id_attendance_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_attendance_records_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_records")),
        sa.UniqueConstraint(
            "recognition_event_id", name="uq_attendance_records_recognition_event"
        ),
        sa.UniqueConstraint(
            "session_id", "student_id", name="uq_attendance_records_session_student"
        ),
    )
    op.create_index(
        "ix_attendance_records_recorded_by_user_id",
        "attendance_records",
        ["recorded_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_attendance_records_student_id",
        "attendance_records",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "attendance_corrections",
        sa.Column("attendance_record_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("previous_status", sa.String(length=16), nullable=False),
        sa.Column("corrected_status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "decision_status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(decision_status = 'pending' AND decided_at IS NULL AND "
            "decided_by_user_id IS NULL) OR "
            "(decision_status IN ('approved', 'rejected') AND "
            "decided_at IS NOT NULL AND decided_by_user_id IS NOT NULL)",
            name=op.f("ck_attendance_corrections_correction_decision_consistency"),
        ),
        sa.CheckConstraint(
            "corrected_status IN ('present', 'late', 'absent', 'excused')",
            name=op.f("ck_attendance_corrections_correction_corrected_status"),
        ),
        sa.CheckConstraint(
            "decision_status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_attendance_corrections_correction_decision"),
        ),
        sa.CheckConstraint(
            "previous_status IN ('present', 'late', 'absent', 'excused')",
            name=op.f("ck_attendance_corrections_correction_previous_status"),
        ),
        sa.CheckConstraint(
            "length(trim(reason)) > 0",
            name=op.f("ck_attendance_corrections_correction_reason_required"),
        ),
        sa.ForeignKeyConstraint(
            ["attendance_record_id"],
            ["attendance_records.id"],
            name=op.f(
                "fk_attendance_corrections_attendance_record_id_attendance_records"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_attendance_corrections_decided_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_attendance_corrections_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_corrections")),
    )
    op.create_index(
        "ix_attendance_corrections_attendance_record_id",
        "attendance_corrections",
        ["attendance_record_id"],
        unique=False,
    )
    op.create_index(
        "ix_attendance_corrections_requested_by_user_id",
        "attendance_corrections",
        ["requested_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_attendance_corrections_requested_by_user_id",
        table_name="attendance_corrections",
    )
    op.drop_index(
        "ix_attendance_corrections_attendance_record_id",
        table_name="attendance_corrections",
    )
    op.drop_table("attendance_corrections")
    op.drop_index("ix_attendance_records_student_id", table_name="attendance_records")
    op.drop_index(
        "ix_attendance_records_recorded_by_user_id", table_name="attendance_records"
    )
    op.drop_table("attendance_records")
    op.drop_index("ix_session_students_student_id", table_name="session_students")
    op.drop_table("session_students")
    op.drop_index(
        "ix_recognition_events_student_occurred_at", table_name="recognition_events"
    )
    op.drop_index(
        "ix_recognition_events_session_occurred_at", table_name="recognition_events"
    )
    op.drop_index(
        "ix_recognition_events_device_occurred_at", table_name="recognition_events"
    )
    op.drop_table("recognition_events")
    op.drop_index(
        "uq_attendance_sessions_active_schedule",
        table_name="attendance_sessions",
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        "ix_attendance_sessions_opened_by_user_id", table_name="attendance_sessions"
    )
    op.drop_table("attendance_sessions")
    op.drop_index(
        "ix_practicum_schedules_teacher_user_id", table_name="practicum_schedules"
    )
    op.drop_index(
        "ix_practicum_schedules_laboratory_weekday", table_name="practicum_schedules"
    )
    op.drop_index(
        "ix_practicum_schedules_class_weekday", table_name="practicum_schedules"
    )
    op.drop_table("practicum_schedules")
    op.drop_index("ix_class_students_student_id", table_name="class_students")
    op.drop_table("class_students")
    op.drop_index("ix_user_roles_role_id", table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(
        "uq_face_templates_active_student_model_version",
        table_name="face_templates",
        postgresql_where=sa.text("revoked_at IS NULL"),
        sqlite_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_face_templates_revoked_by_user_id", table_name="face_templates")
    op.drop_index("ix_face_templates_created_by_user_id", table_name="face_templates")
    op.drop_table("face_templates")
    op.drop_index("ix_devices_laboratory_id", table_name="devices")
    op.drop_table("devices")
    op.drop_index("ix_classes_homeroom_teacher_id", table_name="classes")
    op.drop_table("classes")
    op.drop_index("ix_audit_logs_entity_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("students")
    op.drop_table("roles")
    op.drop_table("laboratories")
    # ### end Alembic commands ###
